[package]
name = "MizzouRL"
version = "0.1.0"
edition = "2021"

[dependencies]
bracket-lib = "0.8.7"
specs = { version = "0.20.0", features = ["serde"] }
specs-derive = "0.4.1"
serde = { version = "1.0.93", features = ["derive"] }
serde_json = "1.0.39"